# Generated by Django 5.1.2 on 2025-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('upper_bp', models.PositiveIntegerField()),
                ('lower_bp', models.PositiveIntegerField()),
                ('hypertension', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('diabetes', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('pedal_edema', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('anemia', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('appetite', models.CharField(choices=[('good', 'Good'), ('poor', 'Poor')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
