# Generated by Django 5.1.2 on 2025-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ckd', '0002_alter_patient_options_remove_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('staff', 'Staff')], max_length=10, null=True),
        ),
    ]
