# Generated by Django 5.1.2 on 2025-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ckd', '0003_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appetite',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bacteria',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('notpresent', 'Not Present')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='coronary_artery_disease',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pedal_edema',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pus_cell',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pus_cell_clumps',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('notpresent', 'Not Present')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='red_blood_cells',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=10, null=True),
        ),
    ]
